apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-derby
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-retain
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-warehouse
  namespace: default
spec:
  accessModes:
   - ReadWriteOncePod
  storageClassName: standard-retain
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs
  namespace: default
spec:
  accessModes:
  - ReadWriteOncePod
  storageClassName: standard-retain
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hivemetastore
  namespace: default
  labels:
    app: hivemetastore

data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
     <property>
       <name>hadoop.proxyuser.hive.hosts</name>
       <value>*</value>
     </property>
     <property>
       <name>hadoop.proxyuser.hive.groups</name>
       <value>*</value>
     </property>
     <property>
       <name>fs.s3a.endpoint</name>
       <value></value>
     </property>
     <property>
       <name>fs.s3a.access.key</name>
       <value></value>
     </property>
       <property>
       <name>fs.s3a.secret.key</name>
       <value></value>
     </property>
    </configuration>

  hive-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>mapred.job.tracker</name>
        <value>local</value>
      </property>
      <property>
        <name>fs.default.name</name>
        <value>file:///opt/hive/tmp/</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:derby:/opt/hive/derby/metastore_db;create=true</value>
      </property>
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>file:///opt/hive/data/warehouse</value>
      </property>
      <property>
        <name>hive.metastore.uris</name>
        <value>thrift://hivemetastore.default.svc.cluster.local:9083</value>
      </property>
      <property>
        <name>datanucleus.schema.autoCreateTables</name>
        <value>true</value>
      </property>
      <property>
        <name>hive.jar.directory</name>
        <value>/opt/hive/lib</value>
      </property>
      <property>
        <name>hive.exec.scratchdir</name>
        <value>/opt/hive/scratch_dir</value>
      </property>
      <property>
        <name>hive.user.install.directory</name>
        <value>/opt/hive/install_dir</value>
      </property>
      <property>
        <name>hive.execution.engine</name>
        <value>tez</value>
      </property>
      <property>
        <name>tez.local.mode</name>
        <value>true</value>
      </property>
      <property>
        <name>tez.runtime.optimize.local.fetch</name>
        <value>true</value>
      </property>
      <property>
        <name>hive.tez.exec.inplace.progress</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.tez.exec.print.summary</name>
        <value>true</value>
      </property>
    </configuration>

  staging.sh: |
    #!/bin/bash
    #
    # STAGING
    #
    set -x
    function staging(){
       echo "Staging ..."
       echo "root:root" | chpasswd
       echo "hive:hive" | chpasswd
       microdnf -y install less vi lsof which net-tools bind-utils hostname netcat-openbsd
       cp ${HIVE_HOME}/setup/*.xml  ${HIVE_HOME}/conf/
       chown -R hive:hive ${HIVE_HOME}
       env
       envVars=$(for v in $(env | grep -v root); do echo "export ${v}" | tr -s '\n' ';' ; done)
       su -s /bin/bash -c "${envVars} ${HIVE_HOME}/setup/start-hive.sh" - hive
    }
    staging
    #EOF

  start-hive.sh: |
    #!/bin/bash
    set -x
    #
    # START HIVE
    #
    function startHive(){     
       #
       # CORRECT ENV VARS
       #
       [ -z "${TEZ_HOME}"  ] && export TEZ_HOME=/opt/tez
       [ -z "${HIVE_HOME}" ] && export HIVE_HOME=/opt/hive && cd ${HIVE_HOME}
       for i in $(env | awk '/_PORT/ && /=tcp:\/\// {gsub(/tcp:\/\/.*:/,"");print $0}'); do 
           echo "Correcting: ${i}"
           export ${i}
       done
       env
       #
       # Link TEZ JARs
       #
       for tezJar in $(ls -1 ${TEZ_HOME}/*.jar | awk -F\/ '{print $NF}'); do
           [ ! -e ${HIVE_HOME}/lib/${tezJar} ] && ln -s ${TEZ_HOME}/${tezJar} ${HIVE_HOME}/lib/${tezJar}
       done
       #
       # INITIALIZE & START HIVE SERVICE
       #
       cd ${HIVE_HOME}
       if [ "${SERVICE}" == "metastore" ]; then
          echo "Initializing ${SERVICE^} schema"
          ${HIVE_HOME}/bin/schematool -dbType derby -initOrUpgradeSchema --verbose
          LOG=${HIVE_HOME}/log/${SERVICE/metastore/hivemetastore}.${HOSTNAME}.$(date +%s).log
       else
          LOG=${HIVE_HOME}/log/${SERVICE}.${HOSTNAME}.$(date +%s).log
       fi
       #
       # Start Hive Service
       #
       ls -lhtr ${HIVE_HOME}
       echo "Starting ${SERVICE^}"
       ${HIVE_HOME}/bin/hive --service ${SERVICE} > ${LOG} 2>&1
       echo $?
       sleep 3600
    }
    #
    # Execute Hive
    #
    id
    #su -s /bin/bash  - hive
    startHive
    #EOF
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive
    component: hivemetastore
  name: hivemetastore
  namespace: default
spec:
  ports:
  - name: thrift
    port: 9083
    protocol: TCP
    targetPort: 9083
  selector:
    app: hive
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hive
    component: hiveserver2
  name: hiveserver2
  namespace: default
spec:
  ports:
  - name: thrift
    port: 10000
    protocol: TCP 
    targetPort: 10000
  - name: http
    port: 10001
    protocol: TCP
    targetPort: 10001
  - name: webui
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: hive
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hive
  name: hive
  namespace: default
spec:
  #
  # Execute as: root
  #
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
  #
  # HMS
  #
  - name: hivemetastore
    env:
    - name: HIVE_VERSION
      value: 4.2.0
    - name: SERVICE_NAME
      value: metastore
    - name: HIVE_HOME
      value: /opt/hive
    - name: SERVICE
      value: metastore
    image: apache/hive:4.2.0
    imagePullPolicy: IfNotPresent
    command: ['/opt/hive/setup/staging.sh']
    volumeMounts:
    - name: mapconfig
      mountPath: /opt/hive/setup
    - name: derby
      mountPath: /opt/hive/derby
    - name: warehouse
      mountPath: /opt/hive/data/warehouse
    - name: logs
      mountPath: /opt/hive/log
    resources: {}
  #
  # HS2
  #
  - name: hiveserver2
    env:
    - name: HIVE_VERSION
      value: 4.2.0
    - name: SERVICE_NAME
      value: hiveserver2
    - name: HIVE_HOME
      value: /opt/hive
    - name: SERVICE
      value: hiveserver2
    image: apache/hive:4.2.0
    imagePullPolicy: IfNotPresent
    command: ['/opt/hive/setup/staging.sh']
    volumeMounts:
    - name: mapconfig
      mountPath: /opt/hive/setup
    - name: warehouse
      mountPath: /opt/hive/data/warehouse
    - name: logs
      mountPath: /opt/hive/log
    resources: {}
  #
  volumes:
  - name: mapconfig
    configMap:
       name: hivemetastore
       defaultMode: 0777
  - name: derby
    persistentVolumeClaim:
      claimName: pvc-derby
  - name: warehouse
    persistentVolumeClaim:
      claimName: pvc-warehouse
  - name: logs
    persistentVolumeClaim:
      claimName: pvc-logs
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
#---
#EOF
